### ISSUE TITLE
SignalAlongPC error when using ATACseq data

### ISSUE THREAD

**Issue by AlexWixom** [databio/COCOA#14]
I've been attempting to run COCOA on ATACseq data and have been running into the following problem when visualizing the signalAlongPC (see bolded text below). I can generate the rsScoreHeatmap without issues. I have tried this with the full Encode_tfbs region database (from LOLA) as well as subsets including only paired samples, single chromosomes (such as chromosome2 seen below) and various other permutations. I have tried every simplification I can think of for the data and still this error persists. I have gone back through the code and this "appears" to be a generated within ComplexHeatmap, but I'm unsure if its due to what is being passed or the heatmap code itself. Your test set will give me output, but my data does not. Any help would be appreciated. 

> signalAlongPC(genomicSignal=onlyUVA,
+                              signalCoord=signalCoord,
+                              regionSet=chr2,
+                              pcScores=pca,
+                              orderByPC="PC1", cluster_columns=TRUE)
Number of cytosines: 6441
Number of regions: 6428
**Error in hclust(get_dist(t(mat), distance), method = method) :
  NA/NaN/Inf in foreign function call (arg 11)**

**Comment by j-lawson** [comment]
@AlexWixom
Hello Alex,

Thanks for using our package! The ATAC-seq version is still under development so it's possible that that visualization function hasn't yet been updated to work with data that has a genomic range (chr start stop) instead of just chr and start as DNA methylation has. We'll take a look at this within the next week and get back to you.

Best,
John

**Comment by AlexWixom** [comment]
Hi John,

I figured this might be the case, so previously this was being run with just the start site being input due to the current statement in your literature saying that if a start and stop are present, they must be the same (http://code.databio.org/COCOA/reference/signalAlongPC.html see signalCoord explanation). I am rerunning it currently without the removal of the end column and will let you know the results. 

Cheers
Alex

**Comment by AlexWixom** [comment]
Unfortunately the same error is output when run with regions rather than a single point. It did increase the number of "cytosines" and "regions" though...
signalAlongPC(genomicSignal=onlyUVA,
                signalCoord=signalCoord,
                regionSet=encode_chr2,
                pcScores=pca,
                orderByPC="PC1", cluster_columns=TRUE,
                column_title = "ATAC peaks",
                name = "TFBS in ATAC peaks")
Number of cytosines: 7442
Number of regions: 473570
Error in hclust(get_dist(t(mat), distance), method = method) :
  NA/NaN/Inf in foreign function call (arg 11)

**Comment by j-lawson** [comment]
Hi Alex,

You could check out the answer to this question on the Bioc support site that had the same error as you: https://support.bioconductor.org/p/45944/. If that doesn't work, it would help if you could provide a very small example of the error (including code and a minimal dataset) so that I could reproduce the error and work to solve it.

Best,
John

**Comment by j-lawson** [comment]
@AlexWixom 

You could also try setting cluster_columns=FALSE if you just want to look at the data since it seems that the clustering is the problem although I think we can still find a fix for the problem.

**Comment by AlexWixom** [comment]
Hi John,

Thank you for posting the link to that forum. By following that and re-looking at the error I was getting, I noticed 2 things:
1) You are already implementing the fix described in the forum.
2) I had been using PC loadings not PC scores when attempting to implement signalAlongPC, when using PC scores, and non-transposed genomicSignal locations, it runs like a charm. 

Thank you for digging into what was end user error. It may be worth adding a:
 prcomp(matrix)$x 
somewhere in the explanation of how to go about running signalAlongPC, since it is using different manipulations of the dataframes than explicitly stated elsewhere in the vignettes. 

Thank you again!

Alex

**Comment by j-lawson** [comment]
Hi Alex,

Glad you got it figured out and thanks for the suggestion!

Best,
John
