### ISSUE TITLE
Running outputs prints

### ISSUE THREAD

**Issue by nsheff** [databio/COCOA#27]
I'm running `runCOCOA` and my screen looks like this: 
![image](https://user-images.githubusercontent.com/5271009/102406568-bfd6f480-3fb8-11eb-936d-3f0ff72c3722.png)

... and just keeps going.

if we have to print something to show computation, can it at least not put a newline? After about 50 of these it looks the same anyway since I can't see my function anymore, and now I can't scroll back my R session.

**Comment by kinganimz** [comment]
At the moment it looks like this: 

![image](https://github.com/databio/COCOA/assets/98941613/707b54cb-5455-4397-82bb-9d8fe4ce857f)

check what else can be done with it

**Comment by kinganimz** [comment]
At the moment looks like this: 
![Zrzut ekranu (97)](https://github.com/databio/COCOA/assets/98941613/337a74d4-0a71-4c42-9cc4-c209d76eaffa)
