### ISSUE TITLE
docs and website

### ISSUE THREAD

**Issue by nsheff** [databio/COCOA#3]
the link "(here)" in the readme is broken

it looks like you're building a pkgdown site for this package; are you planning to render it at `code.databio.org`? If so, it's not working; it would be at: http://code.databio.org/PCRSA

Instructions to do that are here: https://github.com/databio/code.databio.org

Then you should add the above URL to the URL section of this repo.

**Comment by nsheff** [comment]
@j-lawson did you catch this?

**Comment by nsheff** [comment]
also, don't use "here" as link anchor text, use the thing you're linking to

**Comment by nsheff** [comment]
I guess you fixed some of these things in dev, are you going to merge?

**Comment by j-lawson** [comment]
I was waiting for more substantial changes to merge since merging will produce a new Bioc build but I will merge it.

**Comment by nsheff** [comment]
missing: you should add the above URL to the URL section of this repo.
