### ISSUE TITLE
Vignette structure

### ISSUE THREAD

**Issue by nsheff** [databio/COCOA#32]
In the vignette, under basic workflow, it's confusing to have the logic like:

Step 1:
	- Supervised:...
	- Unsupervised: ...
Step 2: 
	- Supervised:...
	- Unsupervised: ...

From a user perspective, I'm making the supervised/unsupervised decision at the beginning. Then, I want to just follow a vignette. So it should be:

Supervised:
	- Step 1
	- Step 2
Unsupervised:
	- Step 1 
	- Step 2

**Comment by kinganimz** [comment]
The regrouping of steps was carried out using: supervised and unsupervised COCOA.
