### ISSUE TITLE
Too much information in documentation

### ISSUE THREAD

**Issue by nsheff** [databio/COCOA#33]
In my opinion, the user-facing documentation of parameters and functions is too verbose. There are a lot of parenthetic statements in descriptions and documentation. In my opinion, if something is not important enough to include outside parenthesis, then 95% of the time it is not important enough to include at all. I found most of the documentation to fall into the "Too Much Information" trap, which distracts from the main point. Many things included in parens are in this category.

Here's an example. I'm trying to figure out what rsOL is. I'm reading this doc, which I cannot really follow:

```
#' @param rsOL a "SortedByQueryHits" object 
#' (output of findOverlaps function). Should have the overlap
#' information between signalCoord and one item of GRList (one unique region set).
#' The region set must be the "subject" in findOverlaps 
#' and signalCoord must be the "query". E.g. findOverlaps(subject=regionSet,
#' query=signalCoord).
#' Providing this information can greatly improve permutation speed since the 
#' overlaps will not have to be calculated for each permutation. 
#' When using this parameter, signalCoord, 
#' genomicSignal, and the region set must be in the same order as they were
#' when olList was created. Otherwise, the wrong genomic loci will be referenced
#' (e.g. if epigenetic features were filtered out of genomicSignal after rsOL
#' was created.) 
```

**Comment by kinganimz** [comment]
I shortened the descriptions.
